// Copyright (c) Mysten Labs, Inc.
// SPDX-License-Identifier: Apache-2.0
//
// Unit tests for deepvault::isqrt (integer Newton sqrt for u128).
//
// The cross-runtime parity test inlines the FIRST 20 cases from the data
// contract at backtest/tests/test_isqrt_random_snapshot.txt, which was
// produced by Plan 01-03 via random.Random(seed=42).randrange(0, 1<<128).
// Move sqrt_u128 MUST produce the same outputs as the Python clone on
// these exact inputs (cross-runtime parity invariant for sqrt — Spike 2
// resolution, see 01-01-SPIKE-NOTES.md).

#[test_only]
module deepvault::isqrt_tests;

use deepvault::isqrt;
use std::unit_test::assert_eq;

#[test]
fun zero_returns_zero() {
    assert_eq!(isqrt::sqrt_u128(0), 0);
}

#[test]
fun small_returns_one() {
    assert_eq!(isqrt::sqrt_u128(1), 1);
    assert_eq!(isqrt::sqrt_u128(2), 1);
    assert_eq!(isqrt::sqrt_u128(3), 1);
}

#[test]
fun perfect_squares() {
    assert_eq!(isqrt::sqrt_u128(4), 2);
    assert_eq!(isqrt::sqrt_u128(9), 3);
    assert_eq!(isqrt::sqrt_u128(100), 10);
    assert_eq!(isqrt::sqrt_u128(10_000), 100);
    assert_eq!(isqrt::sqrt_u128(1_000_000), 1_000);
    // 10^18
    assert_eq!(isqrt::sqrt_u128(1_000_000_000_000_000_000), 1_000_000_000);
}

#[test]
fun off_by_one_floor() {
    assert_eq!(isqrt::sqrt_u128(101), 10);
    assert_eq!(isqrt::sqrt_u128(99), 9);
    assert_eq!(isqrt::sqrt_u128(10001), 100);
    assert_eq!(isqrt::sqrt_u128(9999), 99);
}

#[test]
fun u64_max_minus_one() {
    // floor(sqrt(2^64 - 1)) = 4_294_967_295
    assert_eq!(isqrt::sqrt_u128(18446744073709551615), 4_294_967_295);
}

#[test]
fun u128_max() {
    // floor(sqrt(2^128 - 1)) = 18_446_744_073_709_551_615
    assert_eq!(
        isqrt::sqrt_u128(340282366920938463463374607431768211455),
        18446744073709551615,
    );
}

#[test]
fun initial_guess_is_power_of_two() {
    // The seed must be a power of two by construction (1 << k).
    // Pick a few non-trivial inputs and assert the guess is a power of two.
    let g1 = isqrt::sqrt_initial_guess_u128(100);
    assert!(g1 > 0 && (g1 & (g1 - 1)) == 0);
    let g2 = isqrt::sqrt_initial_guess_u128(1u128 << 100);
    assert!(g2 > 0 && (g2 & (g2 - 1)) == 0);
    let g3 = isqrt::sqrt_initial_guess_u128(0xdeadbeefcafef00d);
    assert!(g3 > 0 && (g3 & (g3 - 1)) == 0);
}

#[test]
fun float_scaling_wrapper_perfect_square() {
    // sqrt(4 * F, F) at scale F = 1e9 should produce 2 * F = 2_000_000_000.
    // Algorithm: scaled = 4*F * (F/F) * F = 4 * F^2; sqrt = 2*F; / multiplier = 2*F.
    let f: u64 = 1_000_000_000;
    assert_eq!(isqrt::sqrt(4 * f, f), 2 * f);
    // sqrt(F) at scale F = sqrt(1.0) = 1.0 = F.
    assert_eq!(isqrt::sqrt(f, f), f);
    // sqrt(0) = 0
    assert_eq!(isqrt::sqrt(0, f), 0);
}

#[test]
fun deterministic_random_inputs_cross_runtime() {
    // First 20 inputs from backtest/tests/test_isqrt_random_snapshot.txt.
    // Format per line: <32-hex-input>=<32-hex-floor-sqrt-output>.
    // Generated by random.Random(42).randrange(0, 1<<128) in Plan 01-03.
    // Cross-runtime parity: Move sqrt_u128 MUST equal Python isqrt_u128.
    let cases: vector<vector<u128>> = vector[
        vector[0xbdd640fb06671ad11c80317fa3b1799d, 0xdc733ad46e8f9b96],
        vector[0xbc8960a923b8c1e9392456de3eb13b90, 0xdbb19ea3e0e811d0],
        vector[0x8b9d2434e465e150bd9c66b3ad3c2d6d, 0xbd0da38ac039243f],
        vector[0x07a0ca6e0822e8f36c031199972a8469, 0x2c30bd8703773426],
        vector[0x9a1de644815ef6d13b8faa1837f8a88b, 0xc6a14b67cdf59a95],
        vector[0x6c307511b2b9437a28df6ec4ce4a2bbd, 0xa66c2ab114329d09],
        vector[0x6142ea7d17be31111a2a73ed562b0f79, 0x9dcb3d41f1bbc7cd],
        vector[0x9a8dca03580d7b71d8f564135be6128e, 0xc6e958c4efb32de4],
        vector[0x60e7a113ec1b8ca1f91e1d4c1ff49b78, 0x9d811ef119964ff7],
        vector[0x93cd59bf5c941cf0dc98d2c1e2acf72f, 0xc284ac33055dad7f],
        vector[0xa9488d990bbb259911ce5dd2b45ed1f0, 0xd02ca11e512c5df1],
        vector[0x614ff3d719db3ad0ddd1dfb23b982ef8, 0x9dd5d01ca3e29e52],
        vector[0x5d65a441d58842dea2bc372f7412b293, 0x9aa09f26a81ecf87],
        vector[0xab9099a435a240ae5af305535ec42e08, 0xd1928a437f5e6599],
        vector[0xa5e5a5abaefcfad8efc89849b3aa7efe, 0xce14e71f89911f14],
        vector[0x6123fdf77656af7229d4beef3eabedcb, 0x9db225803cc05012],
        vector[0xd261a7ab3aa2e4f90e51f30dc6a7ee39, 0xe81290baca3b779e],
        vector[0x448aaa9e66b2bc5b50c187fcce177b4e, 0x8476bd9e1ba16211],
        vector[0xa7cad415366eb16f508ebad7b7c93acf, 0xcf416642dbe84d26],
        vector[0xa491f0b2ea1fca65e27a984d654821d0, 0xcd417b98ec83fb78],
    ];
    let n = cases.length();
    let mut i = 0;
    while (i < n) {
        let row = &cases[i];
        let x = row[0];
        let expected = row[1];
        assert_eq!(isqrt::sqrt_u128(x), expected);
        i = i + 1;
    };
}

#[test, expected_failure(abort_code = isqrt::EInvalidPrecision)]
fun precision_zero_aborts() {
    let _ = isqrt::sqrt(100, 0);
    abort 999
}

#[test, expected_failure(abort_code = isqrt::EInvalidPrecision)]
fun precision_above_float_scaling_aborts() {
    let _ = isqrt::sqrt(100, 1_000_000_001);
    abort 999
}
