// Copyright (c) DeepVault.
// SPDX-License-Identifier: MIT
//
// Property tests for the round-down-in-vault-favor invariant + redeem
// roundtrip + seed-once. Closes the VAULT-09 property-test supplement
// (per CONTEXT.md "Property test scope").
//
// Three tests:
//   1. compute_shares_to_mint_rounds_down_in_vault_favor_50_random_cases —
//      50 (deposit, total_assets, total_shares) tuples generated by
//      Python random.Random(seed=42). Each case asserts
//      compute_shares_to_mint == floor(deposit * (total_shares +
//      virtual_shares) / (total_assets + 1)). The floor on the right is
//      computed in Python at generation time and inlined as the fourth
//      tuple element. Covers Pitfall 12 (round-down-in-vault-favor).
//
//   2. redeem_request_then_fulfill_returns_at_most_proportional_NAV —
//      W5 LOCK: full request -> warp-clock -> fulfill flow with payout
//      assertion. Asserts actual_payout <= expected_payout (proportional
//      NAV bound) AND actual_payout <= seed + extra_balance (liquidity
//      bound). The placeholder discard form documented in the original
//      plan body is REPLACED by the actual fulfill flow with bounds.
//
//   3. create_vault_seed_transaction_succeeds_once — Sui shared-object
//      semantics make a SECOND create_vault call with the same
//      PendingTreasury impossible: PendingTreasury is consumed by value
//      at first call. Test confirms behaviorally that after share::init
//      + share::consume_pending, the PendingTreasury is no longer in
//      the deployer's inventory.
//
// Note on test 2: production `vault::create_vault` calls
// `predict::create_manager(ctx)` which requires a live Predict shared
// object. Pure-Move tests use `vault::new_vault_for_testing` instead
// (the test-only constructor that bypasses Predict). The seeded state
// is identical: 10 DUSDC quote in balance, 1M virtual shares burned to
// @0xdead. This matches the precedent set by Plan 02-05's
// redeem_test.move and Plan 02-04's supply_test.move.

#[test_only]
module deepvault::property_test;

use deepvault::redeem;
use deepvault::share::{Self, SHARE};
use deepvault::strategy_constants;
use deepvault::supply;
use deepvault::vault::{Self, Vault, AdminCap};
use deepvault::vault_test::TEST_QUOTE;
use std::unit_test::assert_eq;
use sui::clock::{Self, Clock};
use sui::coin::{Self, Coin};
use sui::test_scenario as ts;
use sui::test_utils::destroy;

// === Constants used by tests ===

const ADMIN: address = @0xa1;
const USER: address = @0xb2;

/// 1h cooldown plus 1ms safety margin (matches redeem_test.move idiom).
const COOLDOWN_PLUS_1MS: u64 = 3_600_001;

// === Test Helpers ===

/// Build a fresh seeded Vault<TEST_QUOTE> + AdminCap + Clock. After this
/// returns, scenario sender is back to ADMIN at the next `next_tx`.
/// Mirrors `redeem_test::new_seeded_vault` so the two suites stay in sync.
fun new_seeded_vault(
    scenario: &mut ts::Scenario,
): (Vault<TEST_QUOTE>, AdminCap, Clock) {
    share::init_for_testing(scenario.ctx());
    scenario.next_tx(ADMIN);
    let pending = scenario.take_from_sender<share::PendingTreasury>();
    let cap = share::consume_pending(pending);
    let seed_amt = strategy_constants::seed_quote_micro_units();
    let seed = coin::mint_for_testing<TEST_QUOTE>(seed_amt, scenario.ctx());
    let (vault, admin_cap) =
        vault::new_vault_for_testing<TEST_QUOTE>(cap, seed, scenario.ctx());
    let clk = clock::create_for_testing(scenario.ctx());
    (vault, admin_cap, clk)
}

fun cleanup(
    vault: Vault<TEST_QUOTE>,
    admin_cap: AdminCap,
    clk: Clock,
) {
    vault::destroy_for_testing(vault);
    vault::destroy_admin_cap_for_testing(admin_cap);
    clk.destroy_for_testing();
}

/// Returns 50 (deposit, total_assets, total_shares, expected_shares)
/// tuples generated by Python `random.Random(seed=42)` with
/// `expected = (deposit * (total_shares + 1_000_000)) // (total_assets + 1)`.
///
/// Inlined as a Move literal because Sui Move tests cannot read text
/// files at compile time (per STATE.md note on Plan 01-05). Reproducible
/// via `python -c "import random; rng = random.Random(42); ..."` — the
/// generation script is documented in 02-08-SUMMARY.md.
fun random_cases(): vector<vector<u64>> {
    vector[
        vector[123005402501, 834911694991697, 275720902775959, 40621254858],
        vector[151282539206, 115400354428713, 833918052560813, 1093213632288],
        vector[600832337208, 664835551016450, 35783185683417, 32338366465],
        vector[98912226902, 261951004425995, 677812435302673, 255940753666],
        vector[614294295451, 806166225460393, 789623939667401, 601689164075],
        vector[461902007518, 505763420660320, 313217316904940, 286054115461],
        vector[956959218035, 854337752563103, 179760728206845, 201353254423],
        vector[466854954850, 312855479140086, 242421507867504, 361750680819],
        vector[841629822539, 115076514424313, 427757667185489, 3128471627470],
        vector[391257418623, 387259376204435, 297824216222787, 300898936459],
        vector[50711230823, 517267530467920, 140542223941829, 13778303855],
        vector[87525139707, 330087797563249, 707788403842930, 187675156349],
        vector[973319132002, 407166610663745, 216498897198079, 517533889456],
        vector[76040558040, 744515607706649, 870397577186510, 88897421191],
        vector[936645575449, 975572766344568, 427981040942352, 410903792254],
        vector[499410094881, 939127404285359, 183130383509121, 97385256021],
        vector[388136972784, 754549354321710, 790176345877189, 406463345950],
        vector[751347211313, 80391696170027, 714921398453427, 6681712482483],
        vector[584850588137, 275632667796564, 520456249803055, 1104328985439],
        vector[297982493151, 774801974074536, 247263660311673, 95095578907],
        vector[359422682391, 865044403174181, 62980439355513, 26168135101],
        vector[902926887137, 906397161115427, 451668706642492, 449939427995],
        vector[69869416070, 638588387270244, 808299430208302, 88437889560],
        vector[233279766207, 562085195115157, 996064745710608, 413392406096],
        vector[708302589517, 160857095923497, 157209826587166, 692242560629],
        vector[817103044320, 606834055342331, 841063100205820, 1132492836238],
        vector[470662213985, 657000718421749, 407572637966039, 291976911496],
        vector[154608247768, 555650707416872, 850932197038360, 236769492690],
        vector[945095169405, 172082640620981, 180125034319876, 989264809950],
        vector[750726265460, 671498485056360, 433207855193168, 484320550656],
        vector[654474072330, 526979595658777, 283066388138985, 351549877766],
        vector[609761139617, 765930167140880, 128976669408249, 102679023370],
        vector[973590533631, 845415088880052, 865364042705416, 996563998180],
        vector[376415065723, 330450977899881, 178071212394714, 202840033699],
        vector[1948729483, 813007056002636, 810287997855789, 1942212064],
        vector[839668624711, 571596499892148, 119807738461359, 175996178846],
        vector[690933617150, 947634286065448, 571576993018855, 416744904404],
        vector[217363872943, 420989065826301, 181890845977249, 93913362985],
        vector[657132453561, 550122288347835, 125950000607170, 150449882390],
        vector[399127440409, 908350510374585, 269596418933055, 118460140443],
        vector[262241792770, 638789971989304, 88673667942838, 36403110466],
        vector[803526764113, 918760026436961, 599773975811333, 524548771081],
        vector[140728188316, 742810860313053, 185918611730416, 35222949665],
        vector[580958995499, 682963686677530, 850354302259515, 723348827290],
        vector[759049275154, 802708786723167, 449224854201818, 424791414223],
        vector[738713542566, 420432854843150, 508328783322100, 893149411919],
        vector[271102649727, 72087706163791, 23683902736603, 89068849607],
        vector[608117156426, 662525473547027, 8096960179446, 7432017642],
        vector[777693994558, 66286950845750, 75884466483220, 890294302105],
        vector[38248488718, 372029474318145, 578884587419475, 59515339986],
    ]
}

// === Test 1: 50-case round-down-in-vault-favor invariant ===

/// Round-down-in-vault-favor across 50 deterministic cases.
///
/// The formula `(deposit * (total_shares + virtual_shares)) /
/// (total_assets + 1)` truncates toward zero, which rounds DOWN — vault's
/// favor (Pitfall 12). The +1 in the denominator is a second
/// vault-favor lever (it can only ever decrease the result vs a `+0`
/// denominator). The Python expected-floor pre-computed at generation
/// time is the exact integer truncation of the same formula; we assert
/// bit-equality.
#[test]
fun compute_shares_to_mint_rounds_down_in_vault_favor_50_random_cases() {
    let cases = random_cases();
    let n = vector::length(&cases);
    let mut i = 0;
    while (i < n) {
        let case = vector::borrow(&cases, i);
        let deposit = *vector::borrow(case, 0);
        let total_assets = *vector::borrow(case, 1);
        let total_shares = *vector::borrow(case, 2);
        let expected = *vector::borrow(case, 3);

        let actual = supply::compute_shares_to_mint_for_test(
            total_assets,
            total_shares,
            deposit,
        );
        assert_eq!(actual, expected);
        i = i + 1;
    };
}

// === Test 2: redeem_request -> fulfill payout bound (W5 LOCK) ===

/// W5 LOCK — full request/fulfill flow with payout bound assertions.
///
/// Setup:
///   - new_seeded_vault: total_assets = 10M, total_shares = 1M (virtual,
///     burned to @0xdead), balance = 10M.
///   - test_mint_shares_to(user, 100_000): total_shares = 1_100_000;
///     user holds 100k SHARE.
///   - inflate_liquid_for_testing(1_000_000): balance = 11M,
///     total_assets = 11M.
///
/// NAV per share = 11_000_000 * 1e9 / 1_100_000 = 10_000_000_000
///                = 10 quote per share at 1e9 fixed-point.
/// pro_rata for 100_000 shares = 100_000 * 10e9 / 1e9 = 1_000_000.
/// expected_payout = 1_000_000 micro-DUSDC.
///
/// Bucket capacity (100_000_000) and liquid balance (11_000_000) both
/// dwarf pro_rata so the payout equals expected_payout exactly. The
/// `<= expected_payout` form is robust to alternative bucket / balance
/// settings.
///
/// Liquidity bound: actual_payout <= seed_amt + extra_balance =
///                  10_000_000 + 1_000_000 = 11_000_000.
#[test]
fun redeem_request_then_fulfill_returns_at_most_proportional_NAV() {
    let mut scenario = ts::begin(ADMIN);
    let (mut vault, admin_cap, mut clk) = new_seeded_vault(&mut scenario);

    let seed_amt = strategy_constants::seed_quote_micro_units();
    let user_share_amount: u64 = 100_000;
    let user_quote_deposit: u64 = 1_000_000;

    // Mint 100_000 shares directly to USER (W5 helper test_mint_shares_to).
    vault::test_mint_shares_to<TEST_QUOTE>(
        &mut vault,
        USER,
        user_share_amount,
        scenario.ctx(),
    );

    // Inflate liquid balance + total_assets by 1_000_000 micro-DUSDC.
    let extra = coin::mint_for_testing<TEST_QUOTE>(user_quote_deposit, scenario.ctx());
    vault::inflate_liquid_for_testing<TEST_QUOTE>(&mut vault, extra);

    // expected_payout = 100_000 * (10_000_000 + 1_000_000) / (1_000_000 + 100_000)
    //                 = 100_000 * 11_000_000 / 1_100_000
    //                 = 1_000_000 micro-DUSDC.
    let expected_payout: u64 = 1_000_000;

    // Switch to USER and pick up the SHARE coin transferred via test_mint_shares_to.
    scenario.next_tx(USER);
    let user_shares = scenario.take_from_sender<Coin<SHARE>>();
    assert_eq!(coin::value(&user_shares), user_share_amount);

    // Step 1: redeem_request escrows shares + records timestamp at t=0.
    clk.set_for_testing(0);
    redeem::redeem_request<TEST_QUOTE>(&mut vault, user_shares, &clk, scenario.ctx());

    // Step 2: warp clock past the 1h cooldown.
    clk.increment_for_testing(COOLDOWN_PLUS_1MS);

    // Step 3: redeem_fulfill — pays out min(pro_rata, bucket_avail, liquid).
    redeem::redeem_fulfill<TEST_QUOTE>(&mut vault, &clk, scenario.ctx());

    // Capture payout Coin<TEST_QUOTE>.
    scenario.next_tx(USER);
    let payout_coin = scenario.take_from_sender<Coin<TEST_QUOTE>>();
    let actual_payout = coin::value(&payout_coin);

    // W5 assertions (both bounds enforced):
    //   (a) Round-down-in-vault-favor: actual_payout <= expected_payout.
    //   (b) Liquidity bound: actual_payout <= seed + extra_balance.
    assert!(actual_payout <= expected_payout, 9001);
    assert!(actual_payout <= (seed_amt + user_quote_deposit), 9002);

    destroy(payout_coin);
    cleanup(vault, admin_cap, clk);
    scenario.end();
}

// === Test 3: seed-once invariant ===

/// Seed-once invariant: the SHARE module's `init_for_testing` produces
/// exactly one PendingTreasury, which `consume_pending` consumes by
/// value. After consumption, no second PendingTreasury exists in the
/// deployer's inventory — Sui's type system enforces this structurally.
///
/// The production `vault::create_vault` further wraps consume_pending
/// behind a `seed.value() == seed_quote_micro_units()` assert, so the
/// only path that mints virtual_shares + burns them to @0xdead is
/// gated by both the type system AND the seed-amount check. This test
/// confirms the type-level half: a second create_vault call with the
/// SAME PendingTreasury cannot type-check.
#[test]
fun create_vault_seed_transaction_succeeds_once() {
    let mut scenario = ts::begin(ADMIN);

    // First seed: init mints one PendingTreasury to ADMIN's inventory.
    share::init_for_testing(scenario.ctx());
    scenario.next_tx(ADMIN);
    let pending = scenario.take_from_sender<share::PendingTreasury>();

    // Consume it via the public(package) accessor (the same path
    // create_vault uses internally). After this returns, the
    // PendingTreasury is destroyed by value — no second instance exists.
    let cap = share::consume_pending(pending);

    // Assert: ADMIN's inventory no longer contains a PendingTreasury.
    // The Move type system makes a second `take_from_sender<PendingTreasury>`
    // call a runtime error (the test framework returns false from
    // `has_most_recent_for_sender` once the object is consumed).
    scenario.next_tx(ADMIN);
    assert_eq!(
        ts::has_most_recent_for_sender<share::PendingTreasury>(&scenario),
        false,
    );

    // Cleanup: destroy the cap so the test scenario closes cleanly.
    destroy(cap);
    scenario.end();
}
